### ISSUE TITLE
user 提交的作业，是否可以和老师发布的作业在同一页面

### ISSUE THREAD

**Issue by panxiubin** [hackschoolcn/hackschool#100]
user 在提交作业成功后，最好在 ”任务“的部分可以直接看到 user 自己的回复（也就是提交的作业）

**Comment by chpwang** [comment]
这样架构不方便今后扩展，一般来说不同人群的行为不同，所以页面逻辑不同。放一起看似减少了文件数量，但要增加一堆 if 判断，随着网站的发展壮大，会产生无法回头的混乱

**Comment by ghost** [comment]
任务和作业，应该想办法建立联系。点提交作业 进入空白页面，没有任务提示，想不起来要退回去翻。查看作业也是，空白的作业，不知道是对应的哪个任务。

## 任务1 提交作业

http://localhost:3000/account/chapters/1/posts/1
![](http://imageshack.com/a/img921/4913/5PteOs.png)

## 作业提交，忘记任务还要退回去翻。

http://localhost:3000/account/tasks/1/works/new
![](http://imageshack.com/a/img921/9623/CC9LgX.png)

## 作业查看，不知道是对应的哪个任务。

http://localhost:3000/account/tasks/1/works/4
![](http://imageshack.com/a/img922/4737/Wo2wjb.png)

**Comment by yungyuan** [comment]
潘修
