### ISSUE TITLE
「第一次点击」搜索结果可以「成功」显示，「再次点击」同个按钮时出现红色「报错」页面

### ISSUE THREAD

**Issue by lanxinn** [hackschoolcn/hackschool#111]
1、搜索栏輸入「籃球」，跳轉到 http://localhost:3000/account/chapters/search?utf8=✓&query_string=篮球   的链接，搜索结果可以成功显示。

2、链接再次点击搜索按钮，出现ActiveRecord::RecordNotFound in Account::ChaptersController#search 的报错页面。

**Comment by ghost** [comment]
已修复，https://github.com/hackschoolcn/hackschool/pull/130
