### ISSUE TITLE
逻辑架构: 课程内容, 作业, 讨论区, 搜索

### ISSUE THREAD

**Issue by ghost** [hackschoolcn/hackschool#113]
这4块应该要整合在一起，这样看起来比较统一有逻辑。
## 课程内容

http://localhost:3000/account/courses/1/chapters
![](http://imageshack.com/a/img923/1101/7PI8SZ.png)
## 作业

http://localhost:3000/account/courses/1/assignments
![](http://imageshack.com/a/img922/1949/x1ImSK.png)
## 讨论区

http://localhost:3000/account/courses/1/questions
![](http://imageshack.com/a/img924/9664/5luHzR.png)
## 搜索

无处不在的搜索 😓

**Comment by yungyuan** [comment]
週末修
