### ISSUE TITLE
作为user 已经收藏了课程 但是在右上角的地方还是现实 0，应该要现实具体的收藏数会比较合理

### ISSUE THREAD

**Issue by panxiubin** [hackschoolcn/hackschool#171]
<img width="1146" alt="screen shot 2016-09-01 at 10 42 59 am" src="https://cloud.githubusercontent.com/assets/20532854/18153564/fdf1984e-7030-11e6-8329-424f40e31467.png">

**Comment by nieyicheng** [comment]
右上角仅仅作为提醒功能，比如买了课程，块上课之类的提醒，不作其它功能！
