### ISSUE TITLE
user 的下拉选单的“注销”，换成“登出” 可能比较好些

### ISSUE THREAD

**Issue by panxiubin** [hackschoolcn/hackschool#172]
<img width="336" alt="screen shot 2016-09-01 at 10 56 20 am" src="https://cloud.githubusercontent.com/assets/20532854/18153883/d59daec6-7032-11e6-82b2-cd73d12086b1.png">

**Comment by nieyicheng** [comment]
注销容易产生歧义，同意登出或者退出
