### ISSUE TITLE
这里的“注册”和“登入”建议放在navbar的位置比较好

### ISSUE THREAD

**Issue by panxiubin** [hackschoolcn/hackschool#173]
<img width="610" alt="screen shot 2016-09-01 at 10 59 00 am" src="https://cloud.githubusercontent.com/assets/20532854/18153977/679be5d6-7033-11e6-9b28-a1784b96dde3.png">

**Comment by nieyicheng** [comment]
按照正常用户的使用习惯，navbar确实是应该一直有注册和登陆功能
