### ISSUE TITLE
作为 user 忘记密码，点击进去后是 bug

### ISSUE THREAD

**Issue by panxiubin** [hackschoolcn/hackschool#174]
<img width="1297" alt="screen shot 2016-09-01 at 11 03 13 am" src="https://cloud.githubusercontent.com/assets/20532854/18154031/da5c808a-7033-11e6-8adf-cae04808b359.png">

<img width="1214" alt="screen shot 2016-09-01 at 11 03 03 am" src="https://cloud.githubusercontent.com/assets/20532854/18154035/e52edc92-7033-11e6-92b5-1f50fa6ee1a4.png">

**Comment by chpwang** [comment]
已在 Pull Request #221 解决
