### ISSUE TITLE
作为 user 左侧的sidebar 排版不是很好

### ISSUE THREAD

**Issue by panxiubin** [hackschoolcn/hackschool#178]
<img width="208" alt="screen shot 2016-09-01 at 11 15 38 am" src="https://cloud.githubusercontent.com/assets/20532854/18154232/808ee726-7035-11e6-8a32-d1112cd19dca.png">

章节的字体比课程的字体更小

**Comment by nieyicheng** [comment]
需要修改，改成跟随滚动式
