### ISSUE TITLE
作为 user 只有 pre 的功能，没有 next 的功能

### ISSUE THREAD

**Issue by panxiubin** [hackschoolcn/hackschool#179]
<img width="1047" alt="screen shot 2016-09-01 at 11 17 47 am" src="https://cloud.githubusercontent.com/assets/20532854/18154275/d6f4b262-7035-11e6-934e-9fe8b80c0309.png">

建议可以参考一下老师的这个做法，把这两个功能放到页面的最上面
<img width="1247" alt="screen shot 2016-09-01 at 11 18 38 am" src="https://cloud.githubusercontent.com/assets/20532854/18154284/f065074c-7035-11e6-9dd1-6e8a4dd1991b.png">

**Comment by chpwang** [comment]
我已搞定，大家去选择别的 issue bug
