### ISSUE TITLE
有些课程里的标题字体颜色是白色，和底色（白色）重合，看不见字

### ISSUE THREAD

**Issue by panxiubin** [hackschoolcn/hackschool#180]
<img width="971" alt="screen shot 2016-09-01 at 11 20 54 am" src="https://cloud.githubusercontent.com/assets/20532854/18154330/4854e22e-7036-11e6-9aef-10165e26ced8.png">

**Comment by chpwang** [comment]
因为之前 css 影响了全局的 h4 ，目前已解决
