### ISSUE TITLE
作为 user 在“我的课程”和“我的收藏” 里不需要看到 # 以及这一列的数字，看起来很奇怪，不知道什么用处

### ISSUE THREAD

**Issue by panxiubin** [hackschoolcn/hackschool#184]
![screen shot 2016-09-01 at 11 43 14 am](https://cloud.githubusercontent.com/assets/20532854/18154674/58340c6c-7039-11e6-81a3-3c0084a5140e.png)

![screen shot 2016-09-01 at 11 43 25 am](https://cloud.githubusercontent.com/assets/20532854/18154678/64740d24-7039-11e6-9d17-00e25824fb40.png)

**Comment by nieyicheng** [comment]
可以删除
