### ISSUE TITLE
作为 user 缴费成功后，直接进入课程页面。但是课程页面是空的。建议把课程目录放在这一页

### ISSUE THREAD

**Issue by panxiubin** [hackschoolcn/hackschool#186]
![screen shot 2016-09-01 at 11 55 57 am](https://cloud.githubusercontent.com/assets/20532854/18154907/34613a92-703b-11e6-8847-f21be5454446.png)

**Comment by ghost** [comment]
左边就是目录页。

**Comment by panxiubin** [comment]
建议在这一页，左侧放的是 章节名，后侧是详细的目录
