### ISSUE TITLE
admin 帐号新增章节，Edit Post 的时候分页 和全屏 功能 需要新增一个「返回」按钮

### ISSUE THREAD

**Issue by lanxinn** [hackschoolcn/hackschool#199]
<img width="388" alt="2016-09-01 2 01 48" src="https://cloud.githubusercontent.com/assets/20498525/18156922/a89e0c58-704c-11e6-8a7b-e6c72e0a55ad.png">

**Comment by chpwang** [comment]
我已解决了，大家找别的 bug
