### ISSUE TITLE
http://localhost:3000/admin/chapters/9/posts/28 这里的右上角能不能也增加一个编辑按钮

### ISSUE THREAD

**Issue by lanxinn** [hackschoolcn/hackschool#201]
<img width="1019" alt="2016-09-01 2 13 52" src="https://cloud.githubusercontent.com/assets/20498525/18157334/500ec50c-704f-11e6-92d0-a50bd6a3a665.png">

**Comment by chpwang** [comment]
解决了，大家找别的 issue
