### ISSUE TITLE
修改课程详情页与付费页面逻辑

### ISSUE THREAD

**Issue by nieyicheng** [hackschoolcn/hackschool#29]
1.课程详情页需要修改，做成landingpage吸引用户购买
2.在课程详情页点击购买后的页面付费显示方式需要更改
3.点击使用年费或者季费后的页面显示方式与逻辑需要更改
- 需要能显示当前订单是季费还是年费
- 不需要显示订单收件人
- 以友好的界面显示付款价格与付款方式

**Comment by yungyuan** [comment]
訂單詳情頁, 馬師傅

**Comment by ghost** [comment]
已修复。#124。
![](http://imageshack.com/a/img924/1716/QXnDMs.png)
