### ISSUE TITLE
搜索栏未上架的课程仍然可以搜索

### ISSUE THREAD

**Issue by nieyicheng** [hackschoolcn/hackschool#57]
如题

**Comment by ghost** [comment]
已修复 https://github.com/hackschoolcn/hackschool/pull/70
不可见内容不可搜索。

**Comment by chpwang** [comment]
该 bug 还没有修复，用户仍然可以通过输入正确的地址进行搜索

**Comment by ghost** [comment]
已修复。下架课程 用户用原来链接不可搜索。https://github.com/hackschoolcn/hackschool/pull/130
