### ISSUE TITLE
讨论 User 对课程内容搜索的影响范围

### ISSUE THREAD

**Issue by chpwang** [hackschoolcn/hackschool#73]
1、User 在 A 课程中只能搜索 A 课程中的内容。比如 User 只参加了 A 课程和 B 课程，则他在 A 课程的搜索中无法搜索 B 课程的内容，也无法搜索 C 课程的内容（他没参加 C 课程）

2、User 在课程搜索中能搜索他所报名参加（购买）的所有课程的内容。比如 User 只参加了 A 课程和 B 课程，则他在 A 课程的搜索中也能搜索出 B 课程的内容。User 无法搜索他没参加的 C 课程的内容。

3、按照【搜索框】所在的上下文语境来判断。比如【搜索框】在 A 课程页面，就只能搜索 A 课程内容，但如果在课程列表里，就能搜索所有他购买的课的内容。

4、其他选择。

PS：
如果是选择 3，则需要讨论【搜索框】所需要出现的页面和位置（上下文环境选择），因为【搜索框】显然不能随便乱放。

**Comment by yungyuan** [comment]
A搜A,B搜B

**Comment by ghost** [comment]
已修复。A搜A,B搜B。https://github.com/hackschoolcn/hackschool/pull/130
