### ISSUE TITLE
提交作业的相关BUG

### ISSUE THREAD

**Issue by nieyicheng** [hackschoolcn/hackschool#95]
BUG

用户提交作业之后当前页面无法显示提交的内容

在相关课程里当前页面提交作业时会跳到另一个页面

在课程作业页面提交作业后 路径应该还是跳到课程作业的路劲里

在课程作业里提交作业后会报错

**Comment by chpwang** [comment]
【确认操作系统】提交作业后不会跳回【确认操作系统】
