### ISSUE TITLE
课程价格 $ 100 RMB。金钱符号应该为¥。

### ISSUE THREAD

**Issue by ghost** [hackschoolcn/hackschool#99]
路径：http://localhost:3000/courses/1
![](http://imageshack.com/a/img922/4770/cLXTaW.png)

**Comment by ghost** [comment]
http://localhost:3000/courses/1/enroll
![](http://imageshack.com/a/img924/3724/vhihVs.png)

**Comment by yungyuan** [comment]
Lanxinn修
